version: "3.7"

services:
  localstack:
    image: localstack/localstack:0.12.2
    environment:
      SERVICES: sns,sqs,s3
      DEFAULT_REGION: eu-central-1

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: messenger
