name: test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
env:
  GO111MODULE: "on"
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.15.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore vendor
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-vendor-${{ hashFiles('**/go.mod') }}
      - name: Restore base test coverage
        uses: actions/cache@v2
        with:
          path: |
            unit-base.txt
          # Use base sha for PR or new commit hash for master/main push in test result key.
          key: ${{ runner.os }}-test-unit-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}
      - name: Populate dependencies
        if: matrix.go-version == '1.15.x' # Use latest Go to populate vendor.
        run: '(test -d vendor && echo vendor found) || go mod vendor'
      - name: Test
        id: test
        run: |
          make test-unit
          go tool cover -func=./unit.coverprofile > unit.txt
          OUTPUT=$(test -e unit-base.txt && diff -u unit-base.txt unit.txt || grep 'total:' unit.txt)
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=result::$OUTPUT"
      - name: Store master coverage
        if: ${{ github.ref == 'refs/heads/master' }}
        run: cp unit.txt unit-base.txt
      - name: Comment
        if: matrix.go-version == '1.15.x'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: test
          message: |
            ### Unit test coverage
            ```diff
            ${{ steps.test.outputs.result }}
            ```
      - name: Upload code coverage
        if: matrix.go-version == '1.15.x'
        uses: codecov/codecov-action@v1
        with:
          file: ./unit.coverprofile
          flags: unittests
