name: test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
env:
  GO111MODULE: "on"
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.13.x, 1.14.x, 1.15.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore vendor
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-vendor-${{ hashFiles('**/go.mod') }}
      - name: Populate dependencies
        if: matrix.go-version == '1.15.x' # Use latest Go to populate vendor.
        run: '(test -d vendor && echo vendor found) || go mod vendor'
      - name: Test
        id: test
        run: |
          OUTPUT=$(make test-unit)
          echo "::set-output name=result::$OUTPUT"
      - name: Comment
        if: matrix.go-version == '1.15.x'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: test
          message: |
            ```
            LALALAL
            ${{ steps.test.outputs.result }}
            ```
      - name: Upload code coverage
        if: matrix.go-version == '1.15.x'
        uses: codecov/codecov-action@v1
        with:
          file: ./unit.coverprofile
          flags: unittests
